POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Rust rockets",
    "author": "Kostas",
    "url": "http://sdsdsdsd.com",
    "likes": 7,
    "userId": "604bbc854f513cea8fdde172"
}