POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtvc3Rhc18wMiIsImlkIjoiNjA0YzlmMmRkYzA5MzMxNDU0ZWRmZjU3IiwiaWF0IjoxNjE1NjM1ODYzLCJleHAiOjE2MTU2Mzk0NjN9.pUaeY6OlggP-mdrwBpPY9LTKzKa2oAadZh1rTcIYUVw

{
    "title": "Rust better tha golang v.2",
    "author": "random_author",
    "url": "http://sdsdsdsd.com",
    "likes": 17,
    "userId": "604c9f2ddc09331454edff57"
}